[package]
name = "top-down-game"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4.13"
macroquad-canvas-2d = "0.4.0"
macroquad-tiled = "0.2.1"
async-trait = "0.1.83"

[dependencies.macroUtils]
path = "../macroUtils"

